[supervisord]
nodaemon=true
user=root
logfile=/dev/stdout  ; 主日志输出到 stdout
logfile_maxbytes=0   ; 不限制日志大小
pidfile=/var/run/supervisord.pid

[program:ossfs-webdav]
command=/start.sh
stdout_logfile=/dev/stdout  ; 程序 stdout 输出到 stdout
stderr_logfile=/dev/stderr  ; 程序 stderr 输出到 stderr
stdout_logfile_maxbytes=0   ; 不限制日志大小
stderr_logfile_maxbytes=0
autorestart=true
startretries=3
